name: bloc_clean_coding
description: "A Template Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.3
  http: ^1.2.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  formz: ^0.7.0
  logger: ^2.0.2+1
  freezed: ^2.4.7
  google_fonts: ^6.2.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: any





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1




flutter:
  generate: true
  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700